---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: dtocean-app.log
    backupCount: 99
    delay: True
  widget:
    class: dtocean_app.utils.qtlog.QtHandler
    level: DEBUG
    formatter: simple
  widgeterror:
    class: dtocean_app.utils.qtlog.QtHandler
    level: ERROR
    formatter: simple
loggers:
  'dtocean_app':
    level: INFO
    handlers: [widget, file]
    propagate: no
  'dtocean_logistics':
    level: INFO
    handlers: [widget, file]
    propagate: no
  'aneris':
    level: INFO
    handlers: [widgeterror, file]
    propagate: no
root:
  level: INFO
  handlers: [widget, file]

